@startuml "Land Administration System Module Structure"
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

Container_Boundary(boot, "Spring Boot Application") {
    Component(ws, "ws", "REST interfaces")
}

Container_Boundary(command1,"command instance" ) {
    Component(command, "command", "The command handling component")
    Component(commandApi, "command-api", "The commands API")

    Rel_U(command, commandApi, "handles")
}

Component(events, "Events", "The events are the core API in the system")

Rel(command, events, "produces")

Container_Boundary(query1,"query-ladm instance" ) {
    Component(queryLadmApi, "query-ladm-api", "The LADM view API")
    Component(queryLadm, "query-ladm", "The LADM view on the event stream", "Query")
    Rel_U(queryLadm, queryLadmApi, "handles")
    Rel(queryLadm, events, "listens")
}
Container_Boundary(query2,"query-identifiers instance" ) {
    Component(queryIdentifiersApi, "query-identifiers-api", "The identifiers view API")
    Component(queryIdentifiers, "query-identifiers", "The last identifiers in the event stream", "Query")
    Rel_U(queryIdentifiers, queryIdentifiersApi, "handles")
    Rel(queryIdentifiers, events, "listens")
}

Rel(ws, commandApi, "use","AxonServer")
Rel(ws, queryLadmApi, "use","AxonServer")
Rel(ws, queryIdentifiersApi, "use","AxonServer")

@enduml